package tree;

/**
 * Represents a single taxon in the tree
 */
public class Taxon {

    /** The name of this taxon as described by the input file*/
    public String name;

    /** the genome of this taxon as described by the input file*/
    public String genome;

    /** the autogenerated name of this taxon*/
    public String auto_name;

    public Taxon(String name, String auto_name) {
        this.name = name; // real name
        this.auto_name = auto_name;// the auto generated name
    }

}
